{% set name = "dash-mp-components" %}
{% set version = "0.4.39" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_mp_components-{{ version }}.tar.gz
  sha256: 03f8f31f6de7b933066e0ecad3e6d8df0b8e2b5526d0077b6790f8c37ff9c785

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dash
    - dash-core-components
    - dash-html-components
    - dash-table

test:
  imports:
    - dash_mp_components
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Dash components for the Materials Project
  license: BSD-3-Clause-LBNL
  license_file: LICENSE
  home: https://github.com/materialsproject/dash-mp-components

extra:
  recipe-maintainers:
    - awvwgk
